// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2EMw-TUgd0uoPCn4RYSMfMi0pB-vtno',
    appId: '1:745486855520:web:0d5822ed369cc4cf2d4205',
    messagingSenderId: '745486855520',
    projectId: 'kauto-14455',
    authDomain: 'kauto-14455.firebaseapp.com',
    storageBucket: 'kauto-14455.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zosYW1jY3VVTXj_y3oD2QYLZ8oqNBUk',
    appId: '1:745486855520:android:3d799928f3c8b0fa2d4205',
    messagingSenderId: '745486855520',
    projectId: 'kauto-14455',
    storageBucket: 'kauto-14455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVQosMprvuv-4g1xEz-4r-kAIeHCL5SQ',
    appId: '1:745486855520:ios:0741466d5d77098b2d4205',
    messagingSenderId: '745486855520',
    projectId: 'kauto-14455',
    storageBucket: 'kauto-14455.firebasestorage.app',
    androidClientId: '745486855520-krh42juoa97jjcmvcf9f3si2pobtit6q.apps.googleusercontent.com',
    iosClientId: '745486855520-tdtpbss9eshrf833kfjt9ekovl896l3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kauto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVQosMprvuv-4g1xEz-4r-kAIeHCL5SQ',
    appId: '1:745486855520:ios:0741466d5d77098b2d4205',
    messagingSenderId: '745486855520',
    projectId: 'kauto-14455',
    storageBucket: 'kauto-14455.firebasestorage.app',
    androidClientId: '745486855520-krh42juoa97jjcmvcf9f3si2pobtit6q.apps.googleusercontent.com',
    iosClientId: '745486855520-tdtpbss9eshrf833kfjt9ekovl896l3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kauto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM2EMw-TUgd0uoPCn4RYSMfMi0pB-vtno',
    appId: '1:745486855520:web:497d9af86e02c9922d4205',
    messagingSenderId: '745486855520',
    projectId: 'kauto-14455',
    authDomain: 'kauto-14455.firebaseapp.com',
    storageBucket: 'kauto-14455.firebasestorage.app',
  );
}
